### ISSUE TITLE
Automate cert renewal

### ISSUE THREAD

**Issue by Ernaldis** [datajoint/nginx-docker#35]
The process of renewing these certs can be automated, ensuring we are never caught with an expired cert.

To do:
- swap image from letsencrypt to certbot
- remove healthcheck
- add secrets to connect to ec2
- add script to ec2 which
  - removes the previous keys
  - runs compose file
  - commits new keys
  - tags commit
  - pushes tag name to upstream
  - power off
- make github action which
  - runs every two months
  - starts ec2 instance
  - launches startup script

**Comment by yambottle** [comment]
https://github.com/datajoint/nginx-docker/pull/47
